<?php
/**
 * Conditions to display/Hide Tax amount column in 'Items to Invoice' section
 *
 * @category Digitalriver
 * @package  Digitalriver_DrPay
 */
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>

<?php $block->setPriceDataObject($_item)?>
<td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
<td class="col-price">
    <?= $block->getColumnHtml($_item, 'price') ?>
</td>
<td class="col-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
<td class="col-qty-invoice">
    <?php if ($block->canEditQty()): ?>
        <input type="text" class="input-text admin__control-text qty-input"
               name="invoice[items][<?= (int) $_item->getOrderItemId() ?>]"
               value="<?= (float) $_item->getQty() ?>"/>
    <?php else: ?>
        <?= (float) $_item->getQty() ?>
    <?php endif; ?>
</td>
<td class="col-subtotal">
    <?= $block->getColumnHtml($_item, 'subtotal') ?>
</td>
<?php if ($block->getOrder()->getDrDutyFee() === null &&
    $block->getOrder()->getDrIorTax() === null): ?>
    <td class="col-tax"><?= /* @noEscape */ $block->displayPriceAttribute('tax_amount') ?></td>
<?php endif; ?>
<td class="col-discount"><?= /* @noEscape */ $block->displayPriceAttribute('discount_amount') ?></td>
<td class="col-total last">
    <?= $block->getColumnHtml($_item, 'total') ?>
</td>
